### ISSUE TITLE
Error in Insert Into

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#1]
When you declare a var for table, then you should use it in mysql_connector:

``` php
$stmt = $handler->prepare("INSERT into testlist(item,count) VALUES(?,?)");
```

Thanks

**Comment by J-8** [comment]
Hi, sorry I am just responding now.
I forgot to take it out. Sadly it is not possible, at least afaik, to use a variable for the table in prepared statements.
Thanks for your comment!
