### ISSUE TITLE
Update redundant.

### ISSUE THREAD

**Issue by jklmnn** [J-8/ShoppingList_backend#13]
I have just noticed that the update command is not necessary. In the backend, if the command is save, and the item exists, it gets updated. That's actually the same as if you would send the update command. So I'd recommend to drop the update command and only use save.
(To be clear, I'm speaking about the post commands the app sends to the backend. The update function for the database is indeed necessary).

**Comment by J-8** [comment]
The thing is, I left it in because I am unsure what should happen, if you add an item to the list that already exists. Should you get feedback that it already exists? Or do we consider it intentional and therefore add the count to the already existing one.

**Comment by jklmnn** [comment]
The feedback is not given in the api function but in the database function. In both cases, with update and without, the database function update is called. So the feedback will always be correct.
This isn't something serious, so we have time. I will write a test file that can test those things and we'll see.

**Comment by J-8** [comment]
What I am wondering is about the user expirience. What would you personally prefer? Getting feedback that it already exists or quietly adding up the amount?

**Comment by jklmnn** [comment]
You can write 'Item has been saved'. The word save can have both meanings ;)
I would not explicitely say that the item already exists, I would just drop a hint, lets say like 'Item has been updated' instead of 'Item has been created'.

**Comment by J-8** [comment]
Ah, sorry, reading is apparently a skill I have not yet fully mastered.
Yes, you are right. They do the same.

Originally I thought about what happens when an item exists in the list and you add the item again.
Should the user get an error? Or should the amount be updated? That is what i meant earlier when I completely misunderstood your comment;)

**Comment by jklmnn** [comment]
No problem ;)
I think the user should not get an error. I like the current behaviour.
We can't the move the update command anyway now, because your app is still needing it.

**Comment by J-8** [comment]
I think we moved from the app being mine to being ours.
I will, as soon as time lets me, set up a private beta repo so we can experiment a bit.

**Comment by jklmnn** [comment]
Why a private repo? Isn't another branch what was made for this case?

**Comment by J-8** [comment]
A sorry, I meant a private repo in fdroid.

**Comment by jklmnn** [comment]
Ah ok, do you know how to set one up? I've never done that.

**Comment by J-8** [comment]
Do you mean in FDroid? You can just add a new source. But first I have to see if I can figured out how to set up a buildserver:D

**Comment by jklmnn** [comment]
The server side was what I was asking about ;)

**Comment by J-8** [comment]
I just read the manual and it seems straight forward. I have only tried it with prebuilt apks before. But actually building from source does not seem to be too hard. I am at work right now, but I will hopefully have time to try tonight.

**Comment by jklmnn** [comment]
:+1:
