### ISSUE TITLE
make api work with php < 5.6

### ISSUE THREAD

**Issue by the0ne** [J-8/ShoppingList_backend#18]
ubuntu server currently uses
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

so the function http://de2.php.net/hash_equals is not available

i needed to add the following to api.php to use the server api with the app
<?php
if(!function_exists('hash_equals')) {
    function hash_equals($a, $b) {
        $ret = strlen($a) ^ strlen($b);
        $ret |= array_sum(unpack("C*", $a^$b));
        return !$ret;
    }
}
?>

**Comment by ghost** [comment]
So we must add in the Readme that you need PHP 5.6 or we add this script.
