### ISSUE TITLE
Create Option to Create User/Password/Database

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#19]
Create in the Install File an Option to Create a User with Password and Database only for ShoppingList

**Comment by jklmnn** [comment]
The problem is, that this would require access to another user that is able to create the user for ShoppingList.

**Comment by J-8** [comment]
In my case, I have root access and I would prefer if the user in the config.php is not root. So if someone has root access I think we should give the option.
For shared hosting instances the current way of action is sufficient I think.
