### ISSUE TITLE
SQL Template

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#2]
It would be nice to have a SQL Template for the table you need

**Comment by J-8** [comment]
I am writing a littl docu right now. Thanks!

**Comment by ghost** [comment]
Maybe you can look at my requeat fixed some erros in the MySQL file

**Comment by J-8** [comment]
Thanks! Does it work for you? I cannot get it to work with a variable in the prepared statement.

**Comment by J-8** [comment]
Added one. Thanks!
