### ISSUE TITLE
auth key is not accepted

### ISSUE THREAD

**Issue by aslmx** [J-8/ShoppingList_backend#23]
hey there!

followed the instructions in readme.md. I created a new user shoppinglist with its own database and password. I'm using mysql.

I tried to setup the authkey in config.php.

I ran 

php config.php testpassword

i am no expert in this, but shouldn't the hash always be the same? when i run it multiple times i get a new result each time.

root@odroid:/var/www/shoppinglist# php config.php testpassword
$2y$10$TWB8FAZmuec7YM5AJCmLv.qaJIXSgrR7cTIAhI7oQYwSti2LOIMny

root@odroid:/var/www/shoppinglist# php config.php testpassword
$2y$10$V8LRuyvk/IjHXP1eWyzJbuGgfjSzauGtmwPAKZuj2xQvznGhOi9AS

Is there something wrong with my apache or php config maybe? I read that the blowfish hash function is used.

Cant get the app to access the backend... 

any suggestion?

update: cloned the repo again, ran install.php again and this time payed more attention when chosing a password.

still the app says that the auth key is rejected...

Apache log says this btw:

[Tue Aug 25 17:40:38.381868 2015] [:error] [pid 32015] [client 192.168.2.205:47002] PHP Notice:  Undefined index: auth in /var/www/shoppinglist/api.php on line 14

**Comment by ghost** [comment]
No the hash change everytime 
it is feeding with different salt so it is normal no problem

**Comment by ghost** [comment]
Paste your api.php on paste bin and paste your link here

**Comment by aslmx** [comment]
Thanks for the quick response, i just realized that it works when i put the FULL path to api.php in the app settings..

i just had  https://host:port/pathtoshoppinglist/

now i added api.php at the end and it works...

sorry :(

**Comment by ghost** [comment]
It is in error in the app and will be fixed on the next update

**Comment by J-8** [comment]
Don't worry :)  Thanks for your feedback! 

El 25 de agosto de 2015 17:46:57 CEST, aslmx notifications@github.com escribió:

> Thanks for the quick response, i just realized that it works when i put
> the FULL path to api.php in the app settings..
> 
> i just had  https://host:port/pathtoshoppinglist/
> 
> now i added api.php at the end and it works...
> 
> sorry :(
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/J-8/ShoppingList_backend/issues/23#issuecomment-134637453

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
