### ISSUE TITLE
PHP < 5.5

### ISSUE THREAD

**Issue by Black-Fry** [J-8/ShoppingList_backend#24]
For those guys using a php-version lower than 5.5: you will see a blank screen after filling in all fields of http://<your_location>INSTALL.php and hitting the CREATE-button.
The reason for that issue is a FALSE-value as a result from the non-existing "password_hash()"-function. Go and get your copy of the repo at "https://github.com/ircmaxell/password_compat". Put it's files into your shopping-List-directory and last but not least: do not forget to "require 'password_compat-master/lib/password.php';" within INSTALL.php and config.php (if you are hashing your security token manually).

Wasn't that easy to get familliar to this  - anyway, shopping-list is working now. Good job!

**Comment by ghost** [comment]
Sorry for that.
But thanks for that solution.
I will integreat that in the next Version from INSTALL.php

**Comment by J-8** [comment]
Thanks for your feedback!
There are always things that fall through the crack.
