### ISSUE TITLE
Adapt backend to Api

### ISSUE THREAD

**Issue by jklmnn** [J-8/ShoppingList_backend#27]
If https://github.com/J-8/ShoppingList/issues/27 is accepted the databases and php must be adapted.
I would do the SQLite part, and the api.php.

**Comment by ghost** [comment]
Ok I will do MySQL part

**Comment by jklmnn** [comment]
I just had an idea. An item with 0 counts is possible so this just states that all of these item have been done. So we don't need to change the backend as if we just use the count also as state. This would mean that the app (and other clients, I'm currently trying to write a small Gtk+ program) just need to display 'checked' if an Item has 0 counts.
What do you think about that?

**Comment by ghost** [comment]
I think the problem here is, when we change it like some users ask for, that you have no more count, and it is a simple list then it didn't work anymore

**Comment by J-8** [comment]
Okay, get it. I like the idea of the itemCount being 0! However, we need a need way to indicate if an item is important.

**Comment by J-8** [comment]
But if the item is then unchecked, the original count is lost... So maybe we do need a new column for 'checked' and 'favorite'

**Comment by ghost** [comment]
I think we need a table like this

Name,count,star,favourite,deleted

**Comment by J-8** [comment]
Although I would not sync the favorites. So every user can have her/his own ones.

**Comment by ghost** [comment]
ok but wgen i have a mobile and then use the gtk client thete isno sync
i think better

Create users and then share the list with them

**Comment by jklmnn** [comment]
Idk about favourites. I wouldn't do it now because that might be too much at once.
Also user management makes things much more complicated (I still have to admit that this would make bigger installations for many people possible). User management could be also achieved by using folders, lets say like https://example.com/shoppinglist/<user>/api.php where each user has its own config but all could be pointing to the same database with different users.

**Comment by J-8** [comment]
For now that seems impossible for me. I am really busy implementing all the other little things which are complicated enough.

**Comment by jklmnn** [comment]
I would stick with the state (I think that this state is important).
The user management way I described was a way to manage users with the current state of development.

**Comment by J-8** [comment]
I'll close this now as the sync for checked states is in milestone 1.2 for the app. I will open a new issue.
