### ISSUE TITLE
Implement new error handling into api

### ISSUE THREAD

**Issue by J-8** [J-8/ShoppingList_backend#28]
Morning!
I added improved error handling to the app. In my opinion the most important thing :)
So whenever an error is thrown by the api:

``` php
 die (json_encode(array('code' => 'error', 'comment' => 'no database type specified')));
```

it should now be:

``` php
 die (json_encode(array('type' => 1000, 'content' => 'specific error message')));
```

The values of type are all in CONSTANTS.php and the error message will be whatever is in 'content'.
Therefore we can give out new errors, without having to modify the app. So the app will show an error with 'content' as long as the 'type' is >= 5000.

**Comment by ghost** [comment]
and the translations

**Comment by J-8** [comment]
That is true... But for that we could have CONSTANTS_DE.php CONSTANTS_EN.php and so on. But what do you think of it??

**Comment by ghost** [comment]
No i will do it that way

'''
die (json_encode(array('type' => 1000, 'content' => 'specific error message', lang => 'en')));
'''
then in constants.php over switch load lang/en.lang and take here out the Constants default lang de

**Comment by ghost** [comment]
Mean default en

**Comment by J-8** [comment]
The type and content are passed right to the app, so there would be no way to intercept the language of 'content'.
But possibly I just did not understand :)

**Comment by ghost** [comment]
Ok

**Comment by jklmnn** [comment]
I would not use a new identifier, just let code output this number instead of just success or error. Do I understand it right that you want to use it like http codes?

**Comment by J-8** [comment]
Kind of, yes.
The code or rather type and content are used in the app to display the appropriate list/dialog/error. The type helps to categorize the response, for example everything higher than 5000 will be treated as an error and the content will be displayed. That way new errors can be added. The same for everything under 2000, which will be treated as something success happened at the server and the message will be displayed by a toast. So it is a bit more dynamic.

**Comment by J-8** [comment]
I was looking for a way  to make the error reporting to the user more precise and I think that works. But we will see after the next update. I will try to get the app done by Monday so you guys can test if you like.

**Comment by jklmnn** [comment]
I don't really understand the constants. Are they to make programming more easy? 
Should i write `'code' => 5000` or `'code' => 'API_ERROR_SERVER'`. And do we use `code` or `type`?

**Comment by J-8** [comment]
Sorry for being unclear :)
It is easier for me to check for numbers rather then strings. You can write API_ERROR_SERVER (without the quotes, the get replaced by the number at runtime) or the number 5000. But I think it is just easier to read.

**Comment by jklmnn** [comment]
I have changed the sqlite connector now with e4201bf2865c16ca8c7c81f765bd6222e1071b65 and 0a6e996029debc307e0a444342d9de0ed87b7274

**Comment by J-8** [comment]
I changed mysql.
