### ISSUE TITLE
2 new functions to add/delete multiple items

### ISSUE THREAD

**Issue by J-8** [J-8/ShoppingList_backend#30]
To delete or add multiple items at once we need 2 new functions that take every item and count from a json array and add/delete it.

**Comment by J-8** [comment]
Right now the apps makes several request to add/delete each one which seems unnecessary.

**Comment by jklmnn** [comment]
I would change the current functions and not add 2 new ones. We just can send a list with one item if we just want to add/delete one item.
The error handling will be interesting. What do we do if just one of many items fails?

**Comment by J-8** [comment]
You are right.
Good question. And honestly no idea.

**Comment by jklmnn** [comment]
I would stay with the current setting. Neither data nor time are critical in this case.

**Comment by J-8** [comment]
You are right as always ;)  A lot more important things to do.

**Comment by jklmnn** [comment]
I'd close this now. We might reopen it later.

**Comment by J-8** [comment]
I have to reopen. There is no reasonable way to loop through the items. I would have to implement unnecessary checks and variables and I would like to avoid that :/
But the server basically just has to accept a json array and iterate through the items. If there is an error, you can just write whatever you think seems best with the new error handling.

**Comment by jklmnn** [comment]
Maybe we give back an array of `{"item":"<item", "code":code}` objects so we can determine the error/success code for each item.

**Comment by J-8** [comment]
Good idea. But I think maybe for the next release only success or failure is enough. Because otherwise we need a new way to handle that.
