### ISSUE TITLE
Define Project

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#31]
I watch over this project for the last days. And i think what we should do is define a script, milestones or somethink lile this to describe the project. What should the project do and so on
I think else we will lose the overview and the project will be lose a lot off thinks

**Comment by J-8** [comment]
You are absolutely right. I am new to GitHub and have no experience with this.
The things I am currently doing are the way how to modify items and the error handling.

**Comment by ghost** [comment]
We should do more
maybe first create a organisation here then bring the code there 
only to get a better overview it is your code so just a idea

**Comment by ghost** [comment]
So should we be create a orga and define the project?

**Comment by J-8** [comment]
I will hopefully finish my term paper on English Linguistic tomorrow and will then write down my expectations and goals. So far I managed to update the errors, the strike through list, the sharing, and am currently working on marking an item as important. The icon issue and the android api level have also been resolved.

**Comment by ghost** [comment]
What do you think about creating here an organisation, so we could have serveral subproject it is better to control I think

**Comment by J-8** [comment]
Sure go for it, I am happy for every suggestion! As I said, I am inexperienced with github. 

El 28 de agosto de 2015 20:00:58 CEST, Malte Kiefer notifications@github.com escribió:

> What do you think about creating here an organisation, so we could have
> serveral subproject it is better to control I think
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/J-8/ShoppingList_backend/issues/31#issuecomment-135848035

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
What for name for an organisation
@J-8 @jklmnn

**Comment by ghost** [comment]
Ok I create a Orga.
GroundApps, we can change maybe the name but this is the beginning.
You must transfer the repos
So go to the repo, click on Settings, scroll down, click transfer repo
Add name of the Repo, for Orga add GroundApps
Then click Transfer, input your password, wait done

**Comment by jklmnn** [comment]
I like the name.

**Comment by J-8** [comment]
I will do that tonight, still finishing up my term paper... :/

**Comment by J-8** [comment]
Hm it says I cannot transfer because I do not have admin rights for GroundApps.

**Comment by jklmnn** [comment]
Have you been invited? I can't see you in the project.

**Comment by J-8** [comment]
I did not click the link in the invitation...
But now it works:)

**Comment by ghost** [comment]
Also, consider using the 'releases' function of github for an easy tarball download.

Great work, guys!

**Comment by ghost** [comment]
We will do this!
