### ISSUE TITLE
Test new version

### ISSUE THREAD

**Issue by J-8** [J-8/ShoppingList_backend#32]
I finally got something working. If you are interested: https://janb.org/index.php/s/WlODAS0xyeeTKAt
It only works however with the error-handling branch and only for mysql because if have no idea of sqlite.
Feedback please :)

**Comment by J-8** [comment]
Oh and the deletion of items does not work yet because there is no api function. Same for the favorites. And same for important. For the important ones I would like to add a star in the left corner of the row. 
Tell me what you think! Positive and negative!

**Comment by jklmnn** [comment]
SQLite should work now. Why does the deletion not work? Or did you just not implement the deletion function in the app?
I'll test it.

**Comment by J-8** [comment]
I haven't implement it because I didn't know what the api would look like. I will adapt it to your solution.

**Comment by J-8** [comment]
I added multipe save/delete to the mysql_connector. I have however no real knowledge of sqlite and would be happy if you could help out :)

**Comment by jklmnn** [comment]
I'll do when I find time. This week is a bit full for me, but I hope I get it done in the next days.

**Comment by J-8** [comment]
No hurry. Never actually! We do this for fun, so let's keep it that way :)

**Comment by J-8** [comment]
https://janb.org/public.php?service=files&t=DRP3dhAFTBF344c
A couple of new things.
Feedback please as soon as possible, will be out of country between 3.9 and 20.9.
Thanks!

**Comment by J-8** [comment]
https://github.com/GroundApps/ShoppingList/blob/master/app/build/outputs/apk/app-debug.apk
Current build.

**Comment by J-8** [comment]
Have you had the time to test it yet?
I would like to push it to fdroid before Thursday so at least those with errors can better check what the issues are. I will not be back before 20.09.

**Comment by jklmnn** [comment]
I have tested it a bit and I have some things to say:
- If you have not configured the server, the app says that it got a weird response and shows the content of INSTALL.php. There should be a user understandable message.
- I have installed the api with sqlite and added an item. The app crashed on loading then. It seems to fail on listall with a not empty itemlist. This bug is release critical since it makes the app completely unusable.

EDIT: I had some troubles with the branches, I hope I didn't break something ;)
I have tested with the current experimental branch.

**Comment by ghost** [comment]
@jklmnn I have create the branches and changed nothing but I don't know if @J-8 changed something at this Point. :laughing:

**Comment by J-8** [comment]
Hey folks! The issue @jklmnn has is likely due to the mysqli connector not returning the correct type. From what I can tell, the function to check if there have been more than 0 rows always returns true.
The other issue should maybe addressed in the next release with a check if the setup has been completed. 
Greetings from Ireland

**Comment by jklmnn** [comment]
But I have used the sqlite connector. That would mean that both have the wrong return type. What is the right return type?

**Comment by J-8** [comment]
I pushed the update for the app to fdroid. It can take up to 24h for the update to be available. So we need to make sure that whenever the update is available, experimental will replace master.
Fingers crossed ;)
