### ISSUE TITLE
Merge update-new-app-version branch with master

### ISSUE THREAD

**Issue by J-8** [J-8/ShoppingList_backend#35]
Sorry, I did not have the time.
The new app version has been pushed to fdroid and will only work with the new backend.

I hope I can comment while on vacation.
See you then, my flight leaves soon!

**Comment by J-8** [comment]
The Fork continously fails and so I cannot update the app. I will report back as soon as it is fixed.

**Comment by jklmnn** [comment]
The branch experimental is for update-new-app-version and contains some fixes. I'd recommend to use experimental instead.

**Comment by jklmnn** [comment]
I would close this because of #40 if this is ok for you.

**Comment by J-8** [comment]
You're right!
