### ISSUE TITLE
Put backend version in header

### ISSUE THREAD

**Issue by J-8** [J-8/ShoppingList_backend#42]
I think it would be helpful if the app checks if the backend has a certain version to check for compatibility and to give a notice to update. (The update progress we yet have to figure out...)
Right now this would help, because app 1.1 is not compatible with the initial backend.
api.php:

``` php
header("ShoLiBackendVersion: 1");
```

Any comments or should I just implement it?

**Comment by jklmnn** [comment]
Thats a good Idea. I would suggest to use a major and a minor version (eg. 1.0). A major change is incompatible while a minor change just fixes a bug, or adds a feature but older client versions still keep working. This version also should be independent to the software version of the backend.

**Comment by ghost** [comment]
Sorry, guys that I stop working on this. Have a lot of stuff to do right now.
But this idea is good.

**Comment by J-8** [comment]
Implemented with latest commit to experimental.
