### ISSUE TITLE
PPA

### ISSUE THREAD

**Issue by jklmnn** [J-8/ShoppingList_backend#45]
I have created a [PPA](https://launchpad.net/~jklmnn/+archive/ubuntu/groundapps) for the backend. The current package is the version 1.0 and build from the First Release code.
Commit: 03923e5a32c9d63fe17682e6ac6154db831b3e0a

**Comment by jklmnn** [comment]
@beli3ver I just noticed that we also have the UpdateServer repo. I don't know if an update server is still usefull if we have packages?

**Comment by ghost** [comment]
I remove it

**Comment by jklmnn** [comment]
I'll close this issue since this was just a info.
