### ISSUE TITLE
Documentation on how to set up the backend

### ISSUE THREAD

**Issue by davux** [J-8/ShoppingList_backend#5]
There should be minimal documentation on how to set this up (everything, but I'm thinking of MySQL especially).

**Comment by ghost** [comment]
In the meantime a basic guide can be found here: https://github.com/beli3ver/ShoppingList_backend

Thanks, @beli3ver

**Comment by ghost** [comment]
Can somebody check it if it works.
On my Site it didn't work need another pair of eyes

**Comment by ghost** [comment]
Oh, I figured it was my own issues: I've been trying to get it working, too!

Ultimately, I think it'd be nice if @J-8 could shed some light for us. I'm stuck with "The server rejected the supplied auth key!"

Perhaps the android client has a bug with authenticating.

**Comment by J-8** [comment]
Hey guys, sorry, never got an email saying someone posted on here.
I will get to it as soon as I have the time. Honestly never thought anyone would be interested.
Thanks for your comments!

**Comment by ghost** [comment]
No man it could be the opensource alternative to wunderlist
@ainola
In my site it works you need the direct path to API.PHP like this
example.com/shopping/api.php

**Comment by J-8** [comment]
Hey everybody,
I just added a brief README.
Thanks @beli3ver!
Oh, and feedback please! :)

**Comment by davux** [comment]
Thanks guys!
