### ISSUE TITLE
Installation description 

### ISSUE THREAD

**Issue by DaZeller** [J-8/ShoppingList_backend#57]
Hello, 
I've tried to set up the backend, but wasn't successful.
App always displayes "Authentication failed".
Api-Key double checked and OK 
I guess it's something related to access rights on my server?! I also didn't find the SQLlight DB.

Would be great to have a HowTo.

Best regards DaZeller

**Comment by J-8** [comment]
Hey! 
Thanks for you feedback! 
Have you checked the path? 
Is the api reachable on that path with the browser?
The sqlite DB gets created on the first successful connection. However, if the config.php could not be created automatically, this could mean that the webserver user cannot write to the directory.
Sorry, if you know all that stuff, I'd rather give too many details than the other way around.
If you find out what the problem was, you are welcome to write a how to(wiki) or update what we have so far.
Best regards
Jan

**Comment by DaZeller** [comment]
Hi,
Thanks a lot for your quick response!
api.php is reacheable (shows "/\* {"type":5002,"content":"Authentication failed."}" if opend with browser).
Yeah, your right config.php yould not be created by running INSTALL.php the first time.
So I set group and owner for /var/www/html/ShoppingList to www-data. Now INSTALL.php finished with success.
But again the App displays "Authentication failed". (I've e-mailed me the '$authKey' out of the config.php to my mobile and copy 'N' pasted it into the App-settings, so I'm petty sure to made no mistake)
I'm rally no expert in Linux so thanks a lot for your explanation :-)
BR DaZeller

**Comment by jklmnn** [comment]
The auth $authKey in the config.php is encrypted. If you use it in the app it won't work. You have to enter the auth key you've entered in INSTALL.php in the app.
Since you didn't authenticated correctly it won't create a database.

**Comment by J-8** [comment]
Sure! You are welcome to ask any time. I know how difficult things can be in the beginning.... 
Anf like jklmnn said, there is an easy fix to your issue.
The background is that the authkey stored in config.php is just a hash of the actual password. So should the hash become accessible to anyone, it would not be (at least in a reasonable amount of time) be possible to find out the actual password. The password the app sends is also hashed and compared to the stored one.

**Comment by DaZeller** [comment]
OMG, shame over me!
I've just recognized, that there already some '*' in the auth key field if I open the Install.php, I've thought this is a automatic created key...
Sorry for disturbing you and thank you very much for your help!!

**Comment by J-8** [comment]
Never ever apologize for asking something. That is how we learn!
