### ISSUE TITLE
Installation ok, working no

### ISSUE THREAD

**Issue by jinformatique** [J-8/ShoppingList_backend#63]
Hi,

I saw your project and wanted to test it. I did the backend installation on PHP Version 5.6.13.

In the android app, I configured the settings properly and it's the firt time I run the app. I got the message:
`The server did not sent any content back. Likely due to an internal server error.`

Here are my apache log. Can you help me to make the app work?
I choosed SQlite but the file `shoppinglist.sqlite` was not created. How do I initialize it for the first time?

Apache2 acces.log
`[01/Oct/2015:10:37:39 +0200] "POST /sholi/api.php/ HTTP/1.1" 500 2`

Apache2 error.log
`[:error] [pid 31406] [client 10.33.131.37:49095] PHP Notice:  Undefined index: item in /home/jean/web/dev/sholi/api.php on line 13`
`[:error] [pid 31406] [client 10.33.131.37:49095] PHP Notice:  Undefined index: count in /home/jean/web/dev/sholi/api.php on line 14`
`[:error] [pid 31406] [client 10.33.131.37:49095] PHP Notice:  Undefined index: jsonArray in /home/jean/web/dev/sholi/api.php on line 15`
`[:error] [pid 31406] [client 10.33.131.37:49095] PHP Fatal error:  Class 'SQLite3' not found in /home/jean/web/dev/sholi/sqlite_connector.php on line 10`

**Comment by jklmnn** [comment]
`PHP Fatal error: Class 'SQLite3' not found in /home/jean/web/dev/sholi/sqlite_connector.php on line 10` is the important line. You have not installed the SQLite extension for PHP.
Install `php5-sqlite` on Debian based or `php5-pdo` (I'm not sure about this one) on RedHat based systems and restart your apache.

**Comment by jinformatique** [comment]
Ok great. Now it works but when I try to enter an item, I got this error.  
`PHP Fatal error:  Call to a member function fetchArray() on boolean in /home/jean/web/dev/sholi/sqlite_connector.php on line 48`

**Comment by jklmnn** [comment]
That looks like as if the query has failed before. What have you done when this error occured and what other things are working?

**Comment by jinformatique** [comment]
Sorry, I apologize. It was a write permission error on my folder. The file `shoppinglist.sqlite` could not be created. Now it's working fine. Thanks!

**Comment by jklmnn** [comment]
No problem ;)

**Comment by J-8** [comment]
Looks like we should implement a check in install.php if the directory is writeable?

**Comment by ghost** [comment]
It is a simple Check no Problem to implement

Von meinem iPhone gesendet

**Comment by jklmnn** [comment]
Database access is checked in the new PDO. That would have thrown an exception and an error code. I think that's quite enough.
