### ISSUE TITLE
Windows App

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#74]
Hi,

I am superior to create a Windows VB Net App for the Shopping List.
What do you think about it?

**Comment by jklmnn** [comment]
Should we create a Qt App which would run on Linux, Windows and OSX?

**Comment by ghost** [comment]
What you think about GTK.
I don't like Qt

**Comment by jklmnn** [comment]
I've never done something with GTK.
I would prefer something that is easily portable to other platforms (which is Qt).
EDIT: I don't know how portable GTK ist.

**Comment by ghost** [comment]
So we do it in Qt.
Which IDE do you use for QT development?

**Comment by jklmnn** [comment]
The best IDE is the QtCreator which is also available for windows.

**Comment by ghost** [comment]
I switched to Ubuntu.
It is better then upgrade to Windows 10

So lets start

**Comment by jklmnn** [comment]
:)

**Comment by jklmnn** [comment]
https://github.com/GroundApps/ShoppingList_Desktop
